Updated test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,18 +1,26 @@
 #!/usr/bin/env bash
 
-[[ $# -ne 1 ]] && echo "Usage: $(basename $0) /path/to/script" && exit 1
+set -eo pipefail
 
-script="${1}"
+[[ "${TRACE:-}" ]] && set -x
 
-if cmp -s <(${script}) ./test_data; then
-    echo "OK"
-else
-    echo "FAILED"
-    exit 1
-fi
 
-# Time
-echo
-echo "Testing average time"
-echo
-perf stat -n -r 10 -B ${1} >/dev/null
+main() {
+    [[ $# -eq 0 ]] && echo "Usage: $(basename $0) /path/to/script" && exit 1
+    local script=("$@")
+    
+    if cmp -s <("${script[@]}") ./test_data; then
+        echo "OK"
+    else
+        echo "FAILED"
+        exit 1
+    fi
+    
+    # Time
+    echo
+    echo "Testing average time"
+    echo
+    perf stat -n -r 10 -B "${script[@]}" >/dev/null
+}
+
+main "$@"
